language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=flake8
matrix:
  fast_finish: true
install:
  - travis_retry pip install tox==1.6.1
script:
  - travis_retry tox
after_success:
  - coveralls
